import { useEffect, useState, type FormEvent } from 'react';
import { searchAudit, createAuditExport, auditExportStatus, downloadAuditExport } from '../api/teamVault';
import type { SafeAuditPage, AuditExport } from '../api/coreTypes';
export function SafeAuditPanel({ projectId }: { projectId: string }) {
  const [page, setPage] = useState<SafeAuditPage | null>(null); const [action, setAction] = useState(''); const [environment, setEnvironment] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [job, setJob] = useState<AuditExport | null>(null);
  const [window] = useState(() => { const to = new Date(); return { from: new Date(to.getTime() - 31 * 86400000).toISOString(), to: to.toISOString() }; });
  useEffect(() => { let active = true; searchAudit(projectId, new URLSearchParams({ ...window, limit: '100' })).then(data => { if (active) setPage(data); }).catch(error => { if (active) setError(error instanceof Error ? error.message : 'Could not load audit history.'); }); return () => { active = false; }; }, [projectId, window]);
  async function load(cursor = '') { setError(''); setBusy(true); try { setPage(await searchAudit(projectId, new URLSearchParams({ ...window, action, environment, limit: '100', ...(cursor ? { cursor } : {}) }))); } catch (error) { setError(error instanceof Error ? error.message : 'Could not load audit history.'); } finally { setBusy(false); } }
  async function exportSnapshot() { setBusy(true); setError(''); try { setJob(await createAuditExport(projectId, { ...window, action, environment })); } catch (error) { setError(error instanceof Error ? error.message : 'Could not create the audit export.'); } finally { setBusy(false); } }
  async function checkExport() { if (!job) return; setBusy(true); setError(''); try { setJob(await auditExportStatus(projectId, job.id)); } catch (error) { setError(error instanceof Error ? error.message : 'Could not check the export.'); } finally { setBusy(false); } }
  async function download() { if (!job) return; setBusy(true); setError(''); try { const data = await downloadAuditExport(projectId, job.id); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `keepsave-audit-${job.id}.json`; link.click(); URL.revokeObjectURL(url); } catch (error) { setError(error instanceof Error ? error.message : 'Download access could not be confirmed.'); } finally { setBusy(false); } }
  return <section className="cz-card" style={{ padding: 24 }}><h2>Audit activity</h2><p className="cz-muted">Search the last 31 days of safe metadata. Values, provider credentials, proof links, and raw request details are excluded.</p><form className="ks-platform-form" onSubmit={(event: FormEvent) => { event.preventDefault(); void load(); }}><label>Action<input className="cz-input" value={action} onChange={event => setAction(event.target.value)} maxLength={100} placeholder="For example secret.updated" /></label><label>Environment<input className="cz-input" value={environment} onChange={event => setEnvironment(event.target.value)} maxLength={50} placeholder="All environments" /></label><button className="cz-btn" disabled={busy}>Search</button></form>{error && <p role="alert" className="ks-auth-error">{error}</p>}
    {!page && !error && <p role="status">Loading audit history…</p>}<div className="ks-connections-list">{page?.entries.map(item => <div className="ks-connections-row" key={item.id}><div><strong>{item.action}</strong><p>{new Date(item.created_at).toLocaleString()} · {item.environment || 'Project'}</p><p className="cz-muted">{Object.entries(item.references).map(([key, value]) => `${key}: ${value}`).join(' · ')}</p></div></div>)}</div>{page?.next_cursor && <button className="cz-btn" disabled={busy} onClick={() => void load(page.next_cursor)}>Next page</button>}
    <div style={{ marginTop: 24 }}><button className="cz-btn" disabled={busy} onClick={() => void exportSnapshot()}>Create safe metadata export</button><p className="cz-muted">At most 10,000 rows and 20 MiB. The trusted worker publishes the snapshot; downloads expire after one hour and recheck your current access.</p>{job && <div role="status"><p>Export {job.status} · {job.rows} rows</p><button className="cz-btn" disabled={busy} onClick={() => void checkExport()}>Check status</button>{job.status === 'ready' && <button className="cz-btn" disabled={busy} onClick={() => void download()}>Download export</button>}</div>}</div>
  </section>;
}
