# KeepSave Terraform Provider Configuration
#
# This configuration demonstrates how to use KeepSave with Terraform
# to manage secrets as part of infrastructure-as-code workflows.
#
# Usage:
#   1. Set environment variables:
#      export KEEPSAVE_API_URL="https://your-keepsave-instance.com"
#      export KEEPSAVE_TOKEN="your-jwt-token"
#   2. Run: terraform init && terraform plan

terraform {
  required_version = ">= 1.0"
}

variable "keepsave_api_url" {
  description = "KeepSave API URL"
  type        = string
  default     = "http://localhost:8080"
}

variable "keepsave_token" {
  description = "KeepSave JWT token"
  type        = string
  sensitive   = true
}

variable "keepsave_project_id" {
  description = "KeepSave project ID"
  type        = string
}

variable "keepsave_environment" {
  description = "KeepSave environment (alpha, uat, prod)"
  type        = string
  default     = "alpha"
}

# Data source: Pull secrets from KeepSave using external data source
data "external" "keepsave_secrets" {
  program = ["bash", "-c", <<-EOT
    curl -sf \
      -H "Authorization: Bearer ${var.keepsave_token}" \
      -H "Content-Type: application/json" \
      "${var.keepsave_api_url}/api/v1/projects/${var.keepsave_project_id}/secrets?environment=${var.keepsave_environment}" \
    | python3 -c "
    import sys, json
    data = json.load(sys.stdin)
    result = {}
    for s in data.get('secrets', []):
        result[s['key']] = s['value']
    print(json.dumps(result))
    "
  EOT
  ]
}

# Export secrets from KeepSave as .env file
resource "local_file" "env_file" {
  filename = "${path.module}/.env.${var.keepsave_environment}"
  content = join("\n", [
    "# Generated by Terraform + KeepSave",
    "# Environment: ${var.keepsave_environment}",
    "",
    join("\n", [
      for key, value in data.external.keepsave_secrets.result :
      "${key}=${value}"
    ]),
    "",
  ])
  file_permission = "0600"
}

output "secret_keys" {
  description = "List of secret keys pulled from KeepSave"
  value       = keys(data.external.keepsave_secrets.result)
}

output "secrets_count" {
  description = "Number of secrets pulled"
  value       = length(data.external.keepsave_secrets.result)
}
