// Generated by scripts/generate-core-api-types.mjs; edit openapi/core.json.
// This file describes wire shapes. Authority and validation remain server-side.

export type ErrorDetail = {
  "code": number;
  "message": string;
  "error_code"?: string;
};

export type Error = {
  "error": ErrorDetail;
};

export type Unavailable = {
  "error": ErrorDetail;
  "capability": string;
};

export type User = {
  "id": string;
  "email": string;
  "created_at": string;
  "updated_at": string;
};

export type AuthResponse = {
  "user": User;
  "token": string;
};

export type RegisterRequest = {
  "email": string;
  "password": string;
  [key: string]: unknown;
};

export type LoginRequest = {
  "email": string;
  "password": string;
  [key: string]: unknown;
};

export type Providers = {
  "google": boolean;
  "github": boolean;
};

export type SocialStartRequest = {
  "code_challenge": string;
  [key: string]: unknown;
};

export type SocialStart = {
  "authorization_url": string;
  "state": string;
};

export type SocialCompleteRequest = {
  "code": string;
  "state": string;
  "code_verifier": string;
  [key: string]: unknown;
};

export type Connections = {
  "connected": Array<"google" | "github">;
  "available": Providers;
};

export type Linked = {
  "linked": boolean;
};

export type Session = {
  "id": string;
  "current": boolean;
  "created_at": string;
  "expires_at": string;
  "status": "active" | "expired" | "revoked";
  "ip_address": string;
  "user_agent": string;
};

export type Sessions = {
  "sessions": Array<Session>;
};

export type Organization = {
  "id": string;
  "name": string;
  "slug": string;
  "owner_id": string;
  "created_at": string;
  "updated_at": string;
};

export type WorkspaceRequest = {
  "name": string;
  [key: string]: unknown;
};

export type OrganizationResponse = {
  "organization": Organization;
};

export type Organizations = {
  "organizations": Array<Organization>;
};

export type Member = {
  "id": string;
  "organization_id": string;
  "user_id": string;
  "role": "admin" | "editor" | "promoter" | "viewer";
  "created_at": string;
  "updated_at": string;
  "email"?: string;
};

export type MemberResponse = {
  "member": Member;
};

export type Members = {
  "members": Array<Member>;
};

export type AddMemberRequest = {
  "user_id": string;
  "role": "admin" | "editor" | "promoter" | "viewer";
  [key: string]: unknown;
};

export type RoleRequest = {
  "role": "admin" | "editor" | "promoter" | "viewer";
  [key: string]: unknown;
};

export type AssignProjectRequest = {
  "project_id": string;
  [key: string]: unknown;
};

export type Message = {
  "message": string;
};

export type Project = {
  "id": string;
  "name": string;
  "description": string;
  "owner_id": string;
  "allowed_origins": Array<string> | null;
  "embed_policy_enabled": boolean;
  "created_at": string;
  "updated_at": string;
};

export type ProjectRequest = {
  "name": string;
  "description"?: string;
  [key: string]: unknown;
};

export type ProjectResponse = {
  "project": Project;
};

export type Projects = {
  "projects": Array<Project>;
};

export type Secret = {
  "id": string;
  "project_id": string;
  "environment_id": string;
  "key": string;
  "revision"?: number;
  "value"?: string;
  "created_at": string;
  "updated_at": string;
};

export type SecretResponse = {
  "secret": Secret;
};

export type Secrets = {
  "secrets": Array<Secret>;
};

export type CreateSecretRequest = {
  "key": string;
  "value": string;
  "environment": "alpha" | "uat" | "prod";
  [key: string]: unknown;
};

export type UpdateSecretRequest = {
  "value": string;
  "expected_revision"?: number;
  [key: string]: unknown;
};

export type BatchRequest = {
  "environment": "alpha" | "uat" | "prod";
  "keys": Array<string>;
  [key: string]: unknown;
};

export type BatchResponse = {
  "secrets": Array<Secret>;
  "missing_keys": Array<string>;
};

export type Revision = {
  "revision": number;
  "operation": string;
  "created_at": string;
  "actor_id"?: string;
};

export type Record = {
  "id": string;
  "project_id": string;
  "environment": "alpha" | "uat" | "prod";
  "key": string;
  "revision": number;
  "value"?: string;
  "deleted": boolean;
  "environment_id": string;
  "created_at": string;
  "updated_at": string;
};

export type RestoreVersionRequest = {
  "expected_current_revision": number;
  [key: string]: unknown;
};

export type Bundle = {
  "format": string;
  "ciphertext": string;
  "nonce": string;
  "sha256": string;
};

export type Verification = {
  "project_id": string;
  "created_at": string;
  "entries": number;
  "revisions": number;
  "keys": number;
  "snapshots": number;
};

export type RestoreDiff = {
  "secret_id": string;
  "environment": "alpha" | "uat" | "prod";
  "key": string;
  "backup_revision": number;
  "current_revision": number;
  "status": string;
  "restorable": boolean;
};

export type RestorePreview = {
  "project_id": string;
  "backup_created_at": string;
  "records": Array<RestoreDiff>;
};

export type RestoreSelection = {
  "secret_id": string;
  "backup_revision": number;
  "expected_current_revision": number;
};

export type RestoreSelectedRequest = {
  "bundle": Bundle;
  "records": Array<RestoreSelection>;
  [key: string]: unknown;
};

export type RestoredRecords = {
  "records": Array<Record>;
};

export type Capabilities = {
  "profile": "core";
  "application_origin": string;
  "landing_origin": string;
  "restricted_profile": boolean;
  "available": Array<string>;
  "postgresql_only": Array<string>;
  "unavailable": Array<string>;
};

export type BackupMetadata = {
  "id": string;
  "project_id": string;
  "sha256": string;
  "bytes": number;
  "scheduled": boolean;
  "state": "verified" | "delete_pending" | "deleted" | "retention_failed";
  "verified_at": string;
  "created_at": string;
};

export type Backups = {
  "backups": Array<BackupMetadata>;
};

export type ImportEnvironmentRequest = {
  "environment": "alpha" | "uat" | "prod";
  "content": string;
  "overwrite"?: boolean;
};

export type ImportEnvironmentResult = {
  "created": Array<string> | null;
  "updated": Array<string> | null;
  "skipped": Array<string> | null;
};

export type ImportEnvironmentResponse = {
  "result": ImportEnvironmentResult;
};

export type ExportEnvironmentResponse = {
  "content": string;
  "environment": "alpha" | "uat" | "prod";
};

export type RotationResult = {
  "project_id": string;
  "secrets_rotated": number;
  "environments_rotated": number;
};

export type RotationResponse = {
  "message": string;
  "result": RotationResult;
};

export type RotationsResponse = {
  "message": string;
  "results": Array<RotationResult> | null;
};

export type PartialRotationFailure = {
  "error": ErrorDetail;
  "results": Array<RotationResult> | null;
};

export type EncryptionVerification = {
  "status": "healthy" | "degraded";
  "failed_secrets": number;
};

export type PromotionRequest = {
  "source_environment": "alpha" | "uat";
  "target_environment": "uat" | "prod";
  "keys"?: Array<string> | null;
  "override_policy"?: "skip" | "overwrite";
  "notes"?: string;
};

export type PromotionDiffRequest = {
  "source_environment": "alpha" | "uat";
  "target_environment": "uat" | "prod";
  "keys"?: Array<string> | null;
};

export type Promotion = {
  "id": string;
  "project_id": string;
  "source_environment": "alpha" | "uat" | "prod";
  "target_environment": "alpha" | "uat" | "prod";
  "status": "pending" | "approved" | "rejected" | "completed" | "rolled_back";
  "requested_by": string;
  "approved_by"?: string;
  "keys_filter"?: Array<string>;
  "override_policy": string;
  "notes"?: string;
  "created_at": string;
  "completed_at"?: string;
};

export type PromotionResponse = {
  "promotion": Promotion;
};

export type PromotionsResponse = {
  "promotions": Array<Promotion>;
};

export type PromotionDiffEntry = {
  "key": string;
  "action": string;
  "source_hash"?: string;
  "target_hash"?: string;
  "source_exists": boolean;
  "target_exists": boolean;
};

export type PromotionDiffResponse = {
  "diff": Array<PromotionDiffEntry>;
};

export type MessageResponse = {
  "message": string;
};

export type AuditEntry = {
  "id": string;
  "user_id"?: string;
  "project_id"?: string;
  "action": string;
  "environment"?: string;
  "details": {
  [key: string]: unknown;
};
  "ip_address": string;
  "created_at": string;
};

export type AuditResponse = {
  "audit_log": Array<AuditEntry>;
};

export type APIKey = {
  "id": string;
  "name": string;
  "user_id": string;
  "project_id": string;
  "scopes": Array<string>;
  "environment"?: "alpha" | "uat" | "prod";
  "expires_at"?: string;
  "created_at": string;
};

export type CreateAPIKeyRequest = {
  "name": string;
  "project_id": string;
  "scopes"?: Array<string>;
  "environment"?: "alpha" | "uat" | "prod" | null;
  "expires_at"?: string | null;
};

export type CreateAPIKeyResponse = {
  "api_key": APIKey;
  "raw_key": string;
};

export type APIKeysResponse = {
  "api_keys": Array<APIKey>;
};

export type Lease = {
  "id": string;
  "api_key_id": string;
  "project_id": string;
  "environment": "alpha" | "uat" | "prod";
  "secret_keys": Array<string>;
  "granted_at": string;
  "expires_at": string;
  "revoked": boolean;
  "revoked_at"?: string;
};

export type CreateLeaseRequest = {
  "environment": "alpha" | "uat" | "prod";
  "secret_keys": Array<string>;
  "duration_minutes": number;
};

export type LeaseResponse = {
  "lease": Lease;
};

export type LeasesResponse = {
  "leases": Array<Lease> | null;
};

export type MintAgentTokenRequest = {
  "lease_id": string;
  "duration_minutes"?: number;
};

export type MintAgentTokenResponse = {
  "token": string;
  "token_type": "agent";
  "expires_at": string;
  "lease_id": string;
};

export type RevokeAgentTokenRequest = {
  "jti": string;
};

export type Template = {
  "id": string;
  "name": string;
  "description": string;
  "stack": string;
  "keys": {
  [key: string]: unknown;
};
  "created_by": string;
  "organization_id"?: string;
  "is_global": boolean;
  "created_at": string;
  "updated_at": string;
};

export type CreateTemplateRequest = {
  "name": string;
  "description"?: string;
  "stack": string;
  "keys": {
  [key: string]: unknown;
};
  "organization_id"?: string;
  "is_global"?: boolean;
};

export type UpdateTemplateRequest = {
  "name": string;
  "description"?: string;
  "stack": string;
  "keys": {
  [key: string]: unknown;
};
};

export type ApplyTemplateRequest = {
  "project_id": string;
  "environment": "alpha" | "uat" | "prod";
};

export type TemplateResponse = {
  "template": Template;
};

export type TemplatesResponse = {
  "templates": Array<Template>;
};

export type AppliedTemplateResponse = {
  "secrets": Array<Secret> | null;
};

export interface CoreOperations {
  getCapabilities: {
    method: "GET";
    path: "/capabilities";
    request: undefined;
    responses: { "200": Capabilities; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  register: {
    method: "POST";
    path: "/auth/register";
    request: RegisterRequest;
    responses: { "201": AuthResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  login: {
    method: "POST";
    path: "/auth/login";
    request: LoginRequest;
    responses: { "200": AuthResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  logout: {
    method: "POST";
    path: "/auth/logout";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getSignInProviders: {
    method: "GET";
    path: "/auth/providers";
    request: undefined;
    responses: { "200": Providers; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  signInStart: {
    method: "POST";
    path: "/auth/social/{provider}/start";
    request: SocialStartRequest;
    responses: { "200": SocialStart; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  signInComplete: {
    method: "POST";
    path: "/auth/social/{provider}/complete";
    request: SocialCompleteRequest;
    responses: { "200": AuthResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  linkStart: {
    method: "POST";
    path: "/account/connections/{provider}/start";
    request: SocialStartRequest;
    responses: { "200": SocialStart; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  linkComplete: {
    method: "POST";
    path: "/account/connections/{provider}/complete";
    request: SocialCompleteRequest;
    responses: { "200": Linked; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getConnections: {
    method: "GET";
    path: "/account/connections";
    request: undefined;
    responses: { "200": Connections; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listHumanSessions: {
    method: "GET";
    path: "/account/sessions";
    request: undefined;
    responses: { "200": Sessions; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  revokeHumanSession: {
    method: "DELETE";
    path: "/account/sessions/{sessionId}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createWorkspace: {
    method: "POST";
    path: "/organizations";
    request: WorkspaceRequest;
    responses: { "201": OrganizationResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listWorkspaces: {
    method: "GET";
    path: "/organizations";
    request: undefined;
    responses: { "200": Organizations; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getWorkspace: {
    method: "GET";
    path: "/organizations/{orgId}";
    request: undefined;
    responses: { "200": OrganizationResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  updateWorkspace: {
    method: "PUT";
    path: "/organizations/{orgId}";
    request: WorkspaceRequest;
    responses: { "200": OrganizationResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  deleteEmptyWorkspace: {
    method: "DELETE";
    path: "/organizations/{orgId}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  addWorkspaceMember: {
    method: "POST";
    path: "/organizations/{orgId}/members";
    request: AddMemberRequest;
    responses: { "201": MemberResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listWorkspaceMembers: {
    method: "GET";
    path: "/organizations/{orgId}/members";
    request: undefined;
    responses: { "200": Members; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  updateWorkspaceRole: {
    method: "PUT";
    path: "/organizations/{orgId}/members/{userId}";
    request: RoleRequest;
    responses: { "200": MemberResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  removeWorkspaceMember: {
    method: "DELETE";
    path: "/organizations/{orgId}/members/{userId}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listWorkspaceProjects: {
    method: "GET";
    path: "/organizations/{orgId}/projects";
    request: undefined;
    responses: { "200": Projects; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  assignPersonalProject: {
    method: "POST";
    path: "/organizations/{orgId}/projects";
    request: AssignProjectRequest;
    responses: { "200": Message; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createProject: {
    method: "POST";
    path: "/projects";
    request: ProjectRequest;
    responses: { "201": ProjectResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listProjects: {
    method: "GET";
    path: "/projects";
    request: undefined;
    responses: { "200": Projects; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getProject: {
    method: "GET";
    path: "/projects/{id}";
    request: undefined;
    responses: { "200": ProjectResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  updateProject: {
    method: "PUT";
    path: "/projects/{id}";
    request: ProjectRequest;
    responses: { "200": ProjectResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  deleteProject: {
    method: "DELETE";
    path: "/projects/{id}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createSecret: {
    method: "POST";
    path: "/projects/{id}/secrets";
    request: CreateSecretRequest;
    responses: { "201": SecretResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listSecrets: {
    method: "GET";
    path: "/projects/{id}/secrets";
    request: undefined;
    responses: { "200": Secrets; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  readSecretBatch: {
    method: "POST";
    path: "/projects/{id}/secrets/batch";
    request: BatchRequest;
    responses: { "200": BatchResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getSecret: {
    method: "GET";
    path: "/projects/{id}/secrets/{secretId}";
    request: undefined;
    responses: { "200": SecretResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  updateSecret: {
    method: "PUT";
    path: "/projects/{id}/secrets/{secretId}";
    request: UpdateSecretRequest;
    responses: { "200": SecretResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  deleteSecret: {
    method: "DELETE";
    path: "/projects/{id}/secrets/{secretId}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listSecretHistory: {
    method: "GET";
    path: "/projects/{id}/secrets/{secretId}/versions";
    request: undefined;
    responses: { "200": Array<Revision>; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  readSecretVersion: {
    method: "GET";
    path: "/projects/{id}/secrets/{secretId}/versions/{version}";
    request: undefined;
    responses: { "200": Record; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  restoreSecretVersion: {
    method: "POST";
    path: "/projects/{id}/secrets/{secretId}/versions/{version}/restore";
    request: RestoreVersionRequest;
    responses: { "200": Record; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createEncryptedBackup: {
    method: "POST";
    path: "/projects/{id}/backups";
    request: undefined;
    responses: { "201": Bundle; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listEncryptedBackupMetadata: {
    method: "GET";
    path: "/projects/{id}/backups";
    request: undefined;
    responses: { "200": Backups; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  verifyEncryptedBackup: {
    method: "POST";
    path: "/projects/{id}/backups/verify";
    request: Bundle;
    responses: { "200": Verification; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  previewSelectedRestore: {
    method: "POST";
    path: "/projects/{id}/backups/preview";
    request: Bundle;
    responses: { "200": RestorePreview; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  restoreSelectedRecords: {
    method: "POST";
    path: "/projects/{id}/backups/restore";
    request: RestoreSelectedRequest;
    responses: { "200": RestoredRecords; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  importEnvironment: {
    method: "POST";
    path: "/projects/{id}/env-import";
    request: ImportEnvironmentRequest;
    responses: { "200": ImportEnvironmentResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  exportEnvironment: {
    method: "GET";
    path: "/projects/{id}/env-export";
    request: undefined;
    responses: { "200": ExportEnvironmentResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  rotateProjectKey: {
    method: "POST";
    path: "/projects/{id}/rotate-keys";
    request: undefined;
    responses: { "200": RotationResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  verifyProjectEncryption: {
    method: "GET";
    path: "/projects/{id}/verify-encryption";
    request: undefined;
    responses: { "200": EncryptionVerification; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  rotateOwnedProjectKeys: {
    method: "POST";
    path: "/rotate-keys";
    request: undefined;
    responses: { "200": RotationsResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": PartialRotationFailure; "503": Error; };
  };
  promoteEnvironment: {
    method: "POST";
    path: "/projects/{id}/promote";
    request: PromotionRequest;
    responses: { "200": PromotionResponse; "202": PromotionResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  diffEnvironments: {
    method: "POST";
    path: "/projects/{id}/promote/diff";
    request: PromotionDiffRequest;
    responses: { "200": PromotionDiffResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listPromotions: {
    method: "GET";
    path: "/projects/{id}/promotions";
    request: undefined;
    responses: { "200": PromotionsResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getPromotion: {
    method: "GET";
    path: "/projects/{id}/promotions/{promotionId}";
    request: undefined;
    responses: { "200": PromotionResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  approvePromotion: {
    method: "POST";
    path: "/projects/{id}/promotions/{promotionId}/approve";
    request: undefined;
    responses: { "200": PromotionResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  rejectPromotion: {
    method: "POST";
    path: "/projects/{id}/promotions/{promotionId}/reject";
    request: undefined;
    responses: { "200": PromotionResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  rollbackPromotion: {
    method: "POST";
    path: "/projects/{id}/promotions/{promotionId}/rollback";
    request: undefined;
    responses: { "200": MessageResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listProjectAudit: {
    method: "GET";
    path: "/projects/{id}/audit-log";
    request: undefined;
    responses: { "200": AuditResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createAPIKey: {
    method: "POST";
    path: "/api-keys";
    request: CreateAPIKeyRequest;
    responses: { "201": CreateAPIKeyResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listAPIKeys: {
    method: "GET";
    path: "/api-keys";
    request: undefined;
    responses: { "200": APIKeysResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  deleteAPIKey: {
    method: "DELETE";
    path: "/api-keys/{id}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createLease: {
    method: "POST";
    path: "/projects/{id}/leases";
    request: CreateLeaseRequest;
    responses: { "201": LeaseResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listLeases: {
    method: "GET";
    path: "/projects/{id}/leases";
    request: undefined;
    responses: { "200": LeasesResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  revokeLease: {
    method: "DELETE";
    path: "/projects/{id}/leases/{leaseId}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  mintAgentToken: {
    method: "POST";
    path: "/projects/{id}/agent-token";
    request: MintAgentTokenRequest;
    responses: { "201": MintAgentTokenResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  revokeAgentToken: {
    method: "POST";
    path: "/projects/{id}/agent-token/revoke";
    request: RevokeAgentTokenRequest;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  createTemplate: {
    method: "POST";
    path: "/templates";
    request: CreateTemplateRequest;
    responses: { "201": TemplateResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listTemplates: {
    method: "GET";
    path: "/templates";
    request: undefined;
    responses: { "200": TemplatesResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  listBuiltinTemplates: {
    method: "GET";
    path: "/templates/builtin";
    request: undefined;
    responses: { "200": TemplatesResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  getTemplate: {
    method: "GET";
    path: "/templates/{templateId}";
    request: undefined;
    responses: { "200": TemplateResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  updateTemplate: {
    method: "PUT";
    path: "/templates/{templateId}";
    request: UpdateTemplateRequest;
    responses: { "200": TemplateResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  deleteTemplate: {
    method: "DELETE";
    path: "/templates/{templateId}";
    request: undefined;
    responses: { "204": undefined; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
  applyTemplate: {
    method: "POST";
    path: "/templates/{templateId}/apply";
    request: ApplyTemplateRequest;
    responses: { "201": AppliedTemplateResponse; "400": Error; "401": Error; "403": Error; "404": Error; "409": Error; "429": Error; "500": Error; "503": Error; };
  };
}
