apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  master-key: {{ .Values.secrets.masterKey | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
